title: "frourio 入門チュートリアル"
summary: "どんなに TypeScript で型安全に書いたつもりでも、API 通信という割れ窓は回避できません。\n
せめてフロントエンドとバックエンドの API 通信は型安全にしたい！\n
～ みんなの願いを叶える CLI ツール 使い方総集編 ～"
topics: ["TypeScript", "frourio", "aspida"]
published: false
price: 0 # 有料の場合200〜5000
chapters:
  - 01-introduction
  - 02-create-project
  - 03-directory
  - 04-type-check
  - 05-deploy
  - 06-api-definition
  - 07-create-controller
  - 08-inplement-controller
  - 09-geerated-files
