title: "高校生 3 人で 1 年間ウェブ制作をした話"
summary: "第 73 回麻布学園文化祭の公式ウェブサイトを 3 人で制作した 1 年間の記録。"
topics: ["初心者", "ポエム", "Web"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - technology-selection
