title: "第73回麻布学園文化祭 予約・受付・統制システム"
summary: "文化祭の開催形態が揺れる中、一般来場者を招くために設計され、幻に終わったシステムの紹介資料\n\n
＊これは開催形態の決定にあたって教員側に提出した資料を加筆修正したものです。"
topics: ["ポエム"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - construction
  - operation
  - no-lunch-break
  - opinion
  - links
