title: "第 73 回麻布学園文化祭 予約・受付・統制システム"
summary: "一般の来場者を招いての文化祭が不可能となり、幻に終わったシステムの紹介
＊これは開催形態の決定にあたって教員側に提出した資料を加筆修正したものです"
topics: ["ポエム"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - construction
  - operation
  - no-lunch-break
  - opinion
  - links
